[2021-07-18 20:45:40,792] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:45:39.180353+00:00 [queued]>
[2021-07-18 20:45:40,917] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:45:39.180353+00:00 [queued]>
[2021-07-18 20:45:40,918] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 20:45:40,919] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-18 20:45:40,920] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 20:45:41,067] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): Fetching_List_of_Books> on 2021-07-18T20:45:39.180353+00:00
[2021-07-18 20:45:41,109] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Dag', 'Fetching_List_of_Books', '2021-07-18T20:45:39.180353+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Dag.py', '--cfg-path', '/tmp/tmpecvym6b8', '--error-file', '/tmp/tmp_5i09fh_']
[2021-07-18 20:45:41,113] {standard_task_runner.py:77} INFO - Job 5: Subtask Fetching_List_of_Books
[2021-07-18 20:45:41,085] {standard_task_runner.py:52} INFO - Started process 3909 to run task
[2021-07-18 20:45:41,210] {logging_mixin.py:104} INFO - Running <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:45:39.180353+00:00 [running]> on host 3396d0c245ad
[2021-07-18 20:45:41,424] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Dag
AIRFLOW_CTX_TASK_ID=Fetching_List_of_Books
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T20:45:39.180353+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T20:45:39.180353+00:00
[2021-07-18 20:45:41,428] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 20:45:41,431] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'C:/Users/manoj thanneru/***/scripts/List of latest books.py']
[2021-07-18 20:45:41,452] {subprocess.py:74} INFO - Output:
[2021-07-18 20:45:41,463] {subprocess.py:78} INFO - bash: C:/Users/manoj: No such file or directory
[2021-07-18 20:45:41,466] {subprocess.py:82} INFO - Command exited with return code 127
[2021-07-18 20:45:41,499] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-18 20:45:41,502] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Dag, task_id=Fetching_List_of_Books, execution_date=20210718T204539, start_date=20210718T204540, end_date=20210718T204541
[2021-07-18 20:45:41,748] {local_task_job.py:149} INFO - Task exited with return code 1
