[2021-07-18 21:27:42,593] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T21:27:39.580571+00:00 [queued]>
[2021-07-18 21:27:42,672] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T21:27:39.580571+00:00 [queued]>
[2021-07-18 21:27:42,675] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 21:27:42,676] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-18 21:27:42,677] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 21:27:42,795] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): Fetching_List_of_Books> on 2021-07-18T21:27:39.580571+00:00
[2021-07-18 21:27:42,807] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Dag', 'Fetching_List_of_Books', '2021-07-18T21:27:39.580571+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Dag.py', '--cfg-path', '/tmp/tmpsamlv8i2', '--error-file', '/tmp/tmpyqf8l53v']
[2021-07-18 21:27:42,810] {standard_task_runner.py:77} INFO - Job 9: Subtask Fetching_List_of_Books
[2021-07-18 21:27:42,800] {standard_task_runner.py:52} INFO - Started process 6411 to run task
[2021-07-18 21:27:42,983] {logging_mixin.py:104} INFO - Running <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T21:27:39.580571+00:00 [running]> on host 3396d0c245ad
[2021-07-18 21:27:43,220] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Dag
AIRFLOW_CTX_TASK_ID=Fetching_List_of_Books
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T21:27:39.580571+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T21:27:39.580571+00:00
[2021-07-18 21:27:43,224] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 21:27:43,227] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'python /C:/Users/manoj thanneru/***/dags/Scripts/books.py']
[2021-07-18 21:27:43,238] {subprocess.py:74} INFO - Output:
[2021-07-18 21:27:43,340] {subprocess.py:78} INFO - python: can't open file '/C:/Users/manoj': [Errno 2] No such file or directory
[2021-07-18 21:27:43,340] {subprocess.py:82} INFO - Command exited with return code 2
[2021-07-18 21:27:43,355] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-18 21:27:43,358] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Dag, task_id=Fetching_List_of_Books, execution_date=20210718T212739, start_date=20210718T212742, end_date=20210718T212743
[2021-07-18 21:27:43,496] {local_task_job.py:149} INFO - Task exited with return code 1
