[2021-07-18 20:28:52,114] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:28:49.683081+00:00 [queued]>
[2021-07-18 20:28:52,190] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:28:49.683081+00:00 [queued]>
[2021-07-18 20:28:52,191] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 20:28:52,195] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-18 20:28:52,196] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 20:28:52,267] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): Fetching_List_of_Books> on 2021-07-18T20:28:49.683081+00:00
[2021-07-18 20:28:52,278] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Dag', 'Fetching_List_of_Books', '2021-07-18T20:28:49.683081+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Dag.py', '--cfg-path', '/tmp/tmpx0svvuqm', '--error-file', '/tmp/tmplfervphl']
[2021-07-18 20:28:52,280] {standard_task_runner.py:77} INFO - Job 4: Subtask Fetching_List_of_Books
[2021-07-18 20:28:52,271] {standard_task_runner.py:52} INFO - Started process 2914 to run task
[2021-07-18 20:28:52,488] {logging_mixin.py:104} INFO - Running <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:28:49.683081+00:00 [running]> on host 3396d0c245ad
[2021-07-18 20:28:52,872] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Dag
AIRFLOW_CTX_TASK_ID=Fetching_List_of_Books
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T20:28:49.683081+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T20:28:49.683081+00:00
[2021-07-18 20:28:52,883] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 20:28:52,899] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'C:/Users/manoj thanneru/***/scripts/List of latest books.py']
[2021-07-18 20:28:52,934] {subprocess.py:74} INFO - Output:
[2021-07-18 20:28:52,948] {subprocess.py:78} INFO - bash: C:/Users/manoj: No such file or directory
[2021-07-18 20:28:52,958] {subprocess.py:82} INFO - Command exited with return code 127
[2021-07-18 20:28:53,020] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-18 20:28:53,052] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Dag, task_id=Fetching_List_of_Books, execution_date=20210718T202849, start_date=20210718T202852, end_date=20210718T202853
[2021-07-18 20:28:53,421] {local_task_job.py:149} INFO - Task exited with return code 1
