[2021-07-18 21:05:14,791] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T21:05:12.952376+00:00 [queued]>
[2021-07-18 21:05:14,840] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T21:05:12.952376+00:00 [queued]>
[2021-07-18 21:05:14,840] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 21:05:14,841] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-18 21:05:14,841] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 21:05:14,881] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): Fetching_List_of_Books> on 2021-07-18T21:05:12.952376+00:00
[2021-07-18 21:05:14,889] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Dag', 'Fetching_List_of_Books', '2021-07-18T21:05:12.952376+00:00', '--job-id', '7', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Dag.py', '--cfg-path', '/tmp/tmpka5qiyiv', '--error-file', '/tmp/tmpsq55xybk']
[2021-07-18 21:05:14,885] {standard_task_runner.py:52} INFO - Started process 5084 to run task
[2021-07-18 21:05:14,890] {standard_task_runner.py:77} INFO - Job 7: Subtask Fetching_List_of_Books
[2021-07-18 21:05:14,974] {logging_mixin.py:104} INFO - Running <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T21:05:12.952376+00:00 [running]> on host 3396d0c245ad
[2021-07-18 21:05:15,083] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Dag
AIRFLOW_CTX_TASK_ID=Fetching_List_of_Books
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T21:05:12.952376+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T21:05:12.952376+00:00
[2021-07-18 21:05:15,085] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 21:05:15,086] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'C:/Users/manoj thanneru/***/scripts/books.py']
[2021-07-18 21:05:15,096] {subprocess.py:74} INFO - Output:
[2021-07-18 21:05:15,098] {subprocess.py:78} INFO - bash: C:/Users/manoj: No such file or directory
[2021-07-18 21:05:15,099] {subprocess.py:82} INFO - Command exited with return code 127
[2021-07-18 21:05:15,113] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-18 21:05:15,117] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Dag, task_id=Fetching_List_of_Books, execution_date=20210718T210512, start_date=20210718T210514, end_date=20210718T210515
[2021-07-18 21:05:15,266] {local_task_job.py:149} INFO - Task exited with return code 1
