[2021-07-18 20:46:06,995] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:46:05.247646+00:00 [queued]>
[2021-07-18 20:46:07,048] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:46:05.247646+00:00 [queued]>
[2021-07-18 20:46:07,049] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 20:46:07,049] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-18 20:46:07,050] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-18 20:46:07,100] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): Fetching_List_of_Books> on 2021-07-18T20:46:05.247646+00:00
[2021-07-18 20:46:07,104] {standard_task_runner.py:52} INFO - Started process 3942 to run task
[2021-07-18 20:46:07,110] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Dag', 'Fetching_List_of_Books', '2021-07-18T20:46:05.247646+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Dag.py', '--cfg-path', '/tmp/tmpz02uafdg', '--error-file', '/tmp/tmprobpcpe3']
[2021-07-18 20:46:07,111] {standard_task_runner.py:77} INFO - Job 6: Subtask Fetching_List_of_Books
[2021-07-18 20:46:07,233] {logging_mixin.py:104} INFO - Running <TaskInstance: Dag.Fetching_List_of_Books 2021-07-18T20:46:05.247646+00:00 [running]> on host 3396d0c245ad
[2021-07-18 20:46:07,354] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Dag
AIRFLOW_CTX_TASK_ID=Fetching_List_of_Books
AIRFLOW_CTX_EXECUTION_DATE=2021-07-18T20:46:05.247646+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-18T20:46:05.247646+00:00
[2021-07-18 20:46:07,356] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-07-18 20:46:07,357] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'C:/Users/manoj thanneru/***/scripts/List of latest books.py']
[2021-07-18 20:46:07,366] {subprocess.py:74} INFO - Output:
[2021-07-18 20:46:07,368] {subprocess.py:78} INFO - bash: C:/Users/manoj: No such file or directory
[2021-07-18 20:46:07,368] {subprocess.py:82} INFO - Command exited with return code 127
[2021-07-18 20:46:07,388] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-07-18 20:46:07,393] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=Dag, task_id=Fetching_List_of_Books, execution_date=20210718T204605, start_date=20210718T204606, end_date=20210718T204607
[2021-07-18 20:46:07,487] {local_task_job.py:149} INFO - Task exited with return code 1
